
seo:
  description: Marc Gardent

social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/marcgardent'}
- {icon: 'github', link: 'https://github.com/marcgardent'}
- {icon: 'twitter', link: 'https://twitter.com/marcgardent'}
- {icon: 'medium', link: 'https://medium.com/@marcgardent'}

tech:
 devops: [Azure, Terraform, Ansible, Chef, AzureDevOps, Jenkins]
 frontend: [Angular 2+, CSS, HTML, MVC.NET]
 backend: [RabbitMQ, DotNetCore, DotNet, C#, NHibernate, Elastic-Search]

paragraphs:
  vision: |
    > Développer est une activité sociale avant tout!

    J'ai une bonne capacité de projection et d'abstraction.
    Partagez-moi vos besoins en `DevOps`, `Backend` et `Frontend`.
    Nous construirons les meilleures solutions ensemble!
    
  devops: |
    Mon expérience chez **Tessi** m'a ouvert les portes à une pratique du développement proche de la production.
    Ce goût pour la partie infrastructure m'a amené chez **Esker** dans l'équipe de création des environnements `Azure`.

    `Azure`, `Terraform`, `Ansible`, `Chef`, `AzureDevOps`, `Jenkins`, `Prometheus`, `Git`.
  frontend: |
    J'aime travailler sur les différentes technologies web. Et j'ai une attention particulière pour `Angular2+` dans mes projets personnels.

    `Angular2+`, `CSS`, `HTML`, `DotNetCore`.
  backend: |
    De la première ligne de code jusqu'à la mise en production, j'ai créé une plateforme de traitement de document multi-tenant et scalable chez **Tessi**. Et je suis prêt à recommencer!

    `RabbitMQ`, `C# .NET`, `NHibernate`, `PostGreSQL`, `Elastic-Search`.

diploma:
  - title: Degree of Bachelor of science with distinction (Licence)
    location: Napier University, Édimbourg, Ecosse
    date: 2007

  - title: DUT Informatique génie logiciel
    location: Université Pierre Mendès France, Grenoble, France
    date: 2006

  # - title: Baccalauréat Série Scientifique, Spécialité Mathématique
  #   location: Lycée Aristide Bergès, Grenoble, France
  #   date: 2004

footer: |
  Merci!